### ISSUE TITLE
Using invalid values in styles gives blank screen and no warnings/errors

### ISSUE THREAD

**Issue by flubstep** [exponentjs/xde#1]
Summary: If I mess up and put an invalid value for a style, there's no indication of where or how I messed up and where to look for problems.

Repro steps: 
* Find a working Exponent project
* Load the project
* Edit one of the styles to something invalid like fontSize: "13px"
* Reload the project

Result: Blank screen, no warnings, and no warnings in the editor
Expected result: Some sort of error message indicating style mismatch? I'm pretty new to React Native so I'm not sure what I should see. I do know that if I make a syntax error that a warning screen shows up.

**Comment by ccheever** [comment]
We should fix this and can. But in the meantime you can try doing curl on the http version of the URL you get and it will sometimes give you a clue about what's going on.

**Comment by jesseruder** [comment]
React native has better errors around this now:
![2016-08-13 01 11 02](https://cloud.githubusercontent.com/assets/1348527/17640621/6f9afd2e-60b8-11e6-83ab-62b8dd821717.png)
