### ISSUE TITLE
Network requests fail if a proxy is used

### ISSUE THREAD

**Issue by imaffett** [exponentjs/xde#12]
Carrying this over from slack - 

If a user has a proxy configured for their system, network requests fail.  I'm unable to get past the login screen because of this.

https://github.com/exponentjs/xde/blob/master/src/application/Api.js uses the node request library which lets you configure proxies.  

https://github.com/request/request#proxies

Atom uses a .apmrc file to enable apm to make requests over proxies.  - https://discuss.atom.io/t/is-there-any-proxy-settings/710?page=2

**Comment by imaffett** [comment]
Just a note - the XDE will load eventually and I can use it.  Send Link for Phone fails (as expected).

Also, atom has a ~/.atom/.apmrc file that it uses for the proxy settings.  Perhaps you can create a ~/.xde folder (I'd used a different name) and put a .rc file in there to configure any settings.

**Comment by ccheever** [comment]
There is a ~/.exponent directory that probably makes sense for this.
Thanks for the report.

**Comment by imaffett** [comment]
You could add entries to exponent.json that are empty by default.  First pass have users edit it manually, then next pass add a UI option to manage it.

**Comment by imaffett** [comment]
Ok - it looks like the request module *does* handle it for you if proxy settings are configured correctly as environment variables.

http://www.dowdandassociates.com/blog/content/howto-set-an-environment-variable-in-mac-os-x-launchd-plist/

I added http_proxy and https_proxy entries and it works fine.  May be worth updating the readme.md file.  Sorry for the run around!

**Comment by ccheever** [comment]
Oh good to know. Thanks.
