### ISSUE TITLE
source code for examples

### ISSUE THREAD

**Issue by agdolla** [exponentjs/xde#14]
When I run exponent on iphone it allows me to run examples like
@ide/first-experience
@ide/pagescroller
Are these project open sourced ? If yes, where can I find the sources ?
Thanks

**Comment by ccheever** [comment]
Hi @agdolla -

The first-experience project is the template of what gets setup when you do a new project in xde. So just click new and you'll have the code as a starting point to work with.

The page scroller was written by @lelandrichardson and I think you can find it in this repository. https://github.com/lelandrichardson/react_native_animation_examples . @ide just adapted it into an Exponent demo.

Jump in our Slack if you need any help with anything!

**Comment by agdolla** [comment]
thanks
