### ISSUE TITLE
Upgrade to use Node 4 or newer

### ISSUE THREAD

**Issue by ccheever** [exponentjs/xde#18]
We currently are pegged at iojs-2.3.1.
This is because newer versions of iojs and Node had some issues with various libraries and also because the build of Electron that this is built against is using iojs-2.3.1 so it creates a consistent environment.

react-native is now marked as only working against Node 4 and newer. We should upgrade and upgrade the Electron build we are using so that it is also on Node 4+.

**Comment by ide** [comment]
Done as of Electron 0.34
