### ISSUE TITLE
Handle xcrun errors

### ISSUE THREAD

**Issue by jesseruder** [exponentjs/xde#20]
`xcrun` returns error code 69 when user hasn't accepted Xcode license agreement. Catch this and tell the user to run `sudo xcrun cc` or similar to resolve the error.

**Comment by ccheever** [comment]
Do you know a good way to unaccept the license agreement so I can repro and
test this?

**Comment by jesseruder** [comment]
I can't find a way to unaccept the license agreement. It looks like it also might happen when you upgrade Xcode, but I'm not sure.

**Comment by jesseruder** [comment]
It now warns you about accepting the license agreement. Still doesn't forward all errors correctly so leaving open for now.

**Comment by jesseruder** [comment]
Forwards errors correctly now
