### ISSUE TITLE
Add switch between hostname/ip for chrome debugging

### ISSUE THREAD

**Issue by jesseruder** [exponentjs/xde#29]
Hostname doesn't work on Android most of the time, and IP sometimes doesn't work on iOS simulator

**Comment by hendrikswan** [comment]
Hi @jesseruder I can confirm that my issue came from the incorrect Xcode version, as you suggested by sending me this link: http://stackoverflow.com/a/34253285/431522

When I upgraded, my simulator could launch the chrome debugger successfully, and it works like a charm. 

Thanks for all your help on slack!

**Comment by jesseruder** [comment]
@hendrikswan great! I'll close this issue in that case.
