### ISSUE TITLE
Add .gitignore to default project

### ISSUE THREAD

**Issue by nikgraf** [exponentjs/xde#33]
When starting a new project with the App a .gitignore would be nice.

If you like the suggestion I'm happy to create a PR.

**Comment by nikgraf** [comment]
This might do:

```
# OSX
#
.DS_Store

# node.js
#
node_modules/
npm-debug.log

```

**Comment by ide** [comment]
Good idea. If you add a .gitignore file under the `template` directory it should get copied into new projects automatically.
