### ISSUE TITLE
Exponent app crashes on iOS Simulator on load

### ISSUE THREAD

**Issue by mikeislearning** [exponentjs/xde#39]
Just downloaded the Exponent app, and have react-native 0.21.0, and react-native-cli 0.1.10.
I open up the GUI.
Run Simulator - works
Install Exponent on Simulator - works
Open Project in Exponent on Simulator - launch screen shows for 10 seconds, then quits.
Thoughts?

**Comment by joelwass** [comment]
What project are you running? is it an exponent app that you created or that was automatically created by the exponent XDE? if not, is it a react-native project with native dependencies?

**Comment by jesseruder** [comment]
We have new starter projects so this should be fixed

**Comment by sclampet** [comment]
same issue. Any luck?
