### ISSUE TITLE
Error installing Exponent-XDE-osx-1.5.0.zip

### ISSUE THREAD

**Issue by kyawmoehaynes** [exponentjs/xde#41]
![screen shot 2016-03-28 at 2 10 33 pm](https://cloud.githubusercontent.com/assets/7079899/14072168/d4f97220-f4ef-11e5-988b-b943e63d33f8.png)

**Comment by ide** [comment]
Thanks for the report -- we're looking into this.

**Comment by ccheever** [comment]
Hi @kyawmoehaynes --

Sorry you are having this issue. This isn't happening for @ide or for me. Can you try deleting what you have on your computer and downloading from scratch again? If that doesn't fix it, let me know, and I can do a screen share with you and try to debug it on your machine.

**Comment by kyawmoehaynes** [comment]
Hi @ccheever  I tried deleting and downloading from scratch but I'm afraid I'm having the same problem. Could you please help check what's wrong on my machine? Maybe through teamviewer?

**Comment by kyawmoehaynes** [comment]
Sorry I forgot to mention that I was able to install and run v1.4.2. The problem is only with v1.5.0. Thanks.

**Comment by ccheever** [comment]
Very odd that it works fine for everyone on our team. I'll try sending you
a screen share invite using screen hero. If that doesn't work we can try
teamviewer.

**Comment by ccheever** [comment]
@kyawmoehaynes what is an email address i can use for you? if you don't want to post it here, email me at ccheever@exp.host .

**Comment by ccheever** [comment]
This was resolved by changing the security settings on the computer.
