### ISSUE TITLE
Signature is broken for Mac OSX

### ISSUE THREAD

**Issue by cpb** [exponentjs/xde#42]
Verification fails when first launching `Exponent XDE.app`.

Workaround: -[x] Allow apps downloaded from Anywhere

Request: Please get a valid key to sign this with :-)

**Comment by eliatlas** [comment]
1.5.3 still has this issue.
OSX 10.10.5

**Comment by ide** [comment]
Will look into this today. I believe our key is valid (it's not expired and we haven't revoked it), so I think the way we create the app package with electron-packager broke and we didn't notice because our machines were already configured to let XDE run.

**Comment by ide** [comment]
We released a new update (1.5.4) today. We believe the code signing checks out by testing on different Mac machines. It's been tricky to verify because codesign -dv and -vv look normal. But give it a try and let us know if it works for you :)
