### ISSUE TITLE
Exponent crashes on new project run

### ISSUE THREAD

**Issue by cpb** [exponentjs/xde#43]
1. Install XDE on OSX, generate a new project.
2. Use "Send Link for Phone"
3. Open experience URL through the exponent apk.

#### Expected
Hedgehogs and colourful squares like in the screencast

#### Actual
Crash!

**Comment by cpb** [comment]
Seems it is the smsed exp.direct url that wasn't working. I see the example once I publish to exp.host.

**Comment by jesseruder** [comment]
Guessing this was an error starting the tunnel, which should be more stable now. Let me know if that's not the case!
