### ISSUE TITLE
Exponent XDE is damaged cannot be opened

### ISSUE THREAD

**Issue by mak2014** [exponentjs/xde#45]
Downloaded the zip file. Unzipped on Mac osx 10.11.3

When trying to open the app, I am getting this error.
![screen shot 2016-03-30 at 7 35 59 am](https://cloud.githubusercontent.com/assets/10255849/14123051/50ed649e-f64a-11e5-8df1-20fbdfb52cc8.png)

**Comment by ccheever** [comment]
Hi-

Something might be wrong with the way we signed the app, though downloading
and running the release works fine for me.

As a workaround until we can figure out why it's not working for you, you
could try following the steps here and I bet it would work and let you run
the app:
http://www.statsilk.com/support/faq/resolving-mac-only-error-file-damaged-and-should-be-moved-trash

Thanks for the report.
C

**Comment by mak2014** [comment]
Thanks Charlie. It's working
