### ISSUE TITLE
Can I link native bindings for iOS and Android?

### ISSUE THREAD

**Issue by jsdario** [exponentjs/xde#48]
Hi, I want first to say thanks for your work.

However before considering moving a development cycle I'd like to know if we can install packages like `react-native-ble` and use them from exponent, with or without running `rnpm link`.

Thanks again!

**Comment by ide** [comment]
Hi @jsdario! With Exponent we don't support native modules so we might not be the best fit for your product's requirements at this time. But over time, we will build more native modules with documented and maintained APIs to meet more developers' needs. Hope that answers your question.
