### ISSUE TITLE
Missing assets when publishing

### ISSUE THREAD

**Issue by ahanriat** [exponentjs/xde#49]
Hi !
I'm having trouble when publishing my app, images are missing 😢

**Comment by ccheever** [comment]
Hi Antoine-

Are you hosting your images on the internet somewhere or are they just in
the directory with your code?

For now they have to be hosted on the web because everything in exponent
works over the Internet.

We're working on an asset management system right now but it will probably
be a couple weeks before it is rolled out. @nikki93

**Comment by ahanriat** [comment]
Hi @ccheever and thanks for the quick reply ! Yes my assets are in the code directory.
I hope to see the asset management system update soon 😃 

Cheers !

**Comment by ahanriat** [comment]
@ccheever I would like to host my bundle + assets on a server. Is it possible to point on this server from Exponent App instead of using an exponent link ?

**Comment by ahanriat** [comment]
Note I saw there is a json file with containing several information on the bundle (location, ..) but the app doesn't seem to be able to open it, it just open it in a browser

**Comment by ccheever** [comment]
@ahanriat right now, we are just focused on supporting our hosted platform. if you want to do your own custom bundle hosting, etc., you might want to build it yourself. you could also look at something like using microsoft codepush. 

why do you want to host the bundle on your own server? we could consider adding support for that if there's a good reason but so far, we've found most people want that problem solved for them.

**Comment by ahanriat** [comment]
Hosting my bundle on my own server was allowing me benefit from the `fileSystemLocation` and the `httpServerLocation` to have my assets. 
Thanks for your help, I think I'll wait the support for assets system on Exponent 😉

**Comment by ccheever** [comment]
Ok cool. We are working hard on that right now so shouldn't be too long.

**Comment by brentvatne** [comment]
Update to the latest XDE and update your app to SDK 7.0.0 and assets will be published along with your app now :)

**Comment by ahanriat** [comment]
Yeah ! 🎉  Awesome !!
