### ISSUE TITLE
AppImage for Linux

### ISSUE THREAD

**Issue by probonopd** [exponentjs/xde#50]
Would you be interested to provide an [AppImage](http://appimage.org/) for Linux? electron-builder now has support for it that [makes it really easy](https://github.com/electron-userland/electron-builder/issues/504#issuecomment-233170607) to do.

**Comment by jesseruder** [comment]
Yup! Don't officially support Linux yet but I can add this.

**Comment by CrashyBang** [comment]
Hey @jesseruder,

Any update on this?

Cheers.

**Comment by jesseruder** [comment]
Hey sorry, I've been really busy working on other areas. Can definitely prioritize this!

**Comment by jesseruder** [comment]
Took longer than expected but it's here! https://github.com/exponentjs/xde/releases/tag/v2.9.0

Haven't updated the docs yet. Just run `chmod a+x XDE.AppImage` and `./XDE.AppImage`.

**Comment by CrashyBang** [comment]
Hey @jesseruder,

Awesome look forward to trying this out!

Cheers,
Otis.
