### ISSUE TITLE
Won't open on Android simulator.

### ISSUE THREAD

**Issue by donedgardo** [exponentjs/xde#51]
My Emulator is up an running.

On the xde gui i hit Install Android App but this does nothing in the the android emulator.
I choose Device > Open in Android with the same result.

Runing exponent #sdk7.

It runs on my ios simulator, not on android.

**Comment by jesseruder** [comment]
Does running `adb devices` show your android emulator? Also what emulator are you using? Might be a problem with adb version mismatch.

**Comment by donedgardo** [comment]
`adb devices` was giving me problems so i made a fresh homebrew install and now adb is working properly its returning
```shell
List of devices attached
emulator-5554   device
```
restarted packager still no solution.

How to check adb version mismatch against exponents or linking issues?

**Comment by jesseruder** [comment]
Which emulator are you using? XDE bundles its own copy of adb which is probably causing the issue. I need to change it to use the installed copy of adb if its available.

For now you can download the latest APK from here: https://s3.amazonaws.com/exp-android-apks/Exponent-1.6.0.apk and then `adb install` it on your emulator manually. Let me know if that works!

**Comment by jesseruder** [comment]
New XDE should fix this. Let me know if it's working.

**Comment by donedgardo** [comment]
I'll check tonight thank you.

**Comment by jesseruder** [comment]
@donedgardo did that work for you?

**Comment by jesseruder** [comment]
Closing. Let me know if there's still any problems.
