### ISSUE TITLE
"Logs from devices" doesn't appear to be working

### ISSUE THREAD

**Issue by wli** [exponentjs/xde#52]
I don't see any output in the "Logs from devices will appear here" right window, both with Chrome debugging enabled and disabled. I do see logs in the chrome debugger though.

Environment: Android 6.0 (Nexus 5X) via Genymotion, Ubuntu 16.04. SDK v8.0.0

```
$ adb version
Android Debug Bridge version 1.0.36
Revision 0a04cdc4a62f-android
```

**Comment by brentvatne** [comment]
hey @wli, are you importing `exponent` anywhere in your app?

**Comment by wli** [comment]
@brentvatne  I have:

```
Components/FontAwesomeIcon.js:7:import { Font } from 'exponent';
main.js:8:import { Font } from 'exponent';
```

It looks like it works intermittently actually, but not sure what's causing logging to drop.

**Comment by jesseruder** [comment]
Are you running over tunnel, LAN, or localhost?

**Comment by wli** [comment]
localhost

**Comment by jesseruder** [comment]
It looks like we just fixed a bug in exponent-sdk that could have caused this. Can you update to 8.0.6 and see if it's still happening?

**Comment by wli** [comment]
Thanks @jesseruder - I've updated but it doesn't seem to be logging, even after a fresh restart of XDE. Both with and without attaching the debugger.

**Comment by jesseruder** [comment]
Hm ok. Sorry about that. Might be easier to debug this in slack or in person. Can you @ me next time you're working on it?

**Comment by wli** [comment]
Confirmed that the new fix (https://github.com/exponentjs/xdl/commit/2868f94f894cfa22e0ecc8517a85cc6cad8414f1) works - thanks again for fixing this!
