### ISSUE TITLE
Error message/doc improvement for USB debugging

### ISSUE THREAD

**Issue by wli** [exponentjs/xde#53]
When failing to launch XDE app inside android emulator, it has the "Please enable USB debugging" message.

However, the root cause is that there was an adb version mismatch between genymotion's bundled ADB and the ADB that XDE looks for and uses. Once I located the adb directory in genymotion's settings, it starts working again. The error message implies that it's just a matter of enabling USB debugging, but it's unfortunately not the case.

**Comment by brentvatne** [comment]
cc @jesseruder

**Comment by jesseruder** [comment]
Fixed in https://github.com/exponentjs/xdl/commit/aaaf6175ef8555f96d1fe10251a42d7b697ebfac. Cutting a release later today with this.
