### ISSUE TITLE
XDE fails to maintain the logs scroll-lock to the bottom of the logs

### ISSUE THREAD

**Issue by wli** [exponentjs/xde#54]
Results in lots of scrolling to see output.

**Comment by jesseruder** [comment]
Think this is fixed in https://github.com/exponentjs/xde/commit/07d27c9faca5baaf59488c16ddfacb18b8fb2be6. I'll let you confirm before closing

**Comment by wli** [comment]
Thanks @jesseruder this is working fine now!

**Comment by ceefour** [comment]
This doesn't seem to be working as of Expo SDK 2017-12-04 (I'm not sure what version it is, since there is no intutitive way to get its version. Additionally: Help > Send Diagnostics Report is not working. Additionally: There are two "Help" menus, each one are different)
