### ISSUE TITLE
XDE overwrites ngrok config file

### ISSUE THREAD

**Issue by sprice** [exponentjs/xde#59]
XDE installation seems to overwrite `~/.ngrok2/ngrok.yml`

I use ngrok for personal development. After installing XDE, when I try to run ngrok with `ngrok http -hostname=me.ngrok.io 3000` I get the error:
```
Tunnel session failed: This domain is reserved for another account.
Failed to bind the domain 'sp.ngrok.io' for the account 'Exponent'.
```

I noticed the file ~/~ngrok2/original1.ngrok.yml`. I coped the `authtoken` from this file back into `ngrok.yml` and now I can use ngrok for personal development.

**Comment by jesseruder** [comment]
Fixed in v2.8.0. Thanks!
