### ISSUE TITLE
Exponent app reinstalls every time iOS Simulator opens

### ISSUE THREAD

**Issue by kembuco** [exponentjs/xde#66]
XDE 2.9.0 - Mac OSX 10.12 - iOS Simulator 10.0

**Actual**
1) iOS Simulator is closed
2) Click on "Device" toolbar item in XDE
3) Choose "Open on iOS Simulator
4) Notice following error message in XDE Logs:

```
12:18:27 PM Opening iOS simulator
12:18:27 PM Opening exp://localhost:19000 in iOS simulator
12:18:41 PM Error running `xcrun simctl openurl booted exp://localhost:19000`: 
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=60):
The operation couldn’t be completed. Operation timed out Operation timed out
12:18:41 PM Error running app. Uninstalling exponent and trying again.
12:18:41 PM Uninstalling Exponent from iOS simulator.
12:18:41 PM Downloading latest version of Exponent
12:18:42 PM Installing Exponent on iOS simulator
12:18:46 PM Opening exp://localhost:19000 in iOS simulator
```

**Expected**
Exponent app should not be uninstalled and reinstalled every time.

**Comment by jesseruder** [comment]
I think this is a bug with the simulator. See: http://stackoverflow.com/questions/24233589/xcode6-cant-run-any-app-in-simulator-domain-nsposixerrordomain-code-3

Looks like people have had success with rebooting or clearing the simulator

**Comment by kembuco** [comment]
Sorry again for not searching better for a solution.  I just switched my hardware device in the simulator and then switched it back.  Not sure what it jostled, but everything is working again.

**Comment by jesseruder** [comment]
No worries, thanks for letting us know! I'll add a note to add some suggestions when this error happens

**Comment by shettyrahul8june** [comment]
I am facing this too. But, happens when I remotely debug.

**Comment by brentvatne** [comment]
@shettyrahul8june - can you provide exact repro steps? what platform? simulator/emulator or device?

**Comment by shettyrahul8june** [comment]
@brentvatne Sure.

**Steps to reproduce:**

1. Start Expo XDE
2. Go to your respective project
3. Once the project is opened, Click on Devices -> Open on iOS Simulator.
4. Simulator (iPhone 6 - iOS 10.3) fires up.
5. Javascript builds successfully and the project starts successfully but below is the error that I get:

![image](https://cloud.githubusercontent.com/assets/8545078/25691655/ad901c2c-30ba-11e7-8647-f83db3582e33.png)

**Comment by brentvatne** [comment]
@shettyrahul8june - did you read the original answer by @jesseruder? This can happen when the iOS simulator is in a bad state, the solution is to [Reset Content and Settings](http://stackoverflow.com/questions/2763733/how-to-reset-iphone-simulator)

**Comment by shettyrahul8june** [comment]
I read. And I did reset and start everything again. But, I still see the error.

**Comment by brentvatne** [comment]
@shettyrahul8june - this isn't really anything to do with Expo, it's an iOS simulator error :( you might have better luck googling what the source of that error is and making sure all of your apple developer tools are up to date

**Comment by shettyrahul8june** [comment]
@brentvatne Yea. I realised.

**Comment by martinezguillaume** [comment]
I've got the same error

**Comment by tetreault** [comment]
@martinezguillaume I had the issue too, but as @brentvatne kept saying this isn't an Expo problem but instead is an issue with the ios simulator. 

I eventually quit expo, re-opened, selected my project to open it, once open restarted the project, then opened the ios simulator. I still see the error now and then but my project opens successfully in the simulator.

**Comment by ODelibalta** [comment]
I have this issue as well.

**Comment by Arieg419** [comment]
I have this issue as well.

Currently updating mac os sierra and then will update xcode. Hope it solves the problem.

**Comment by jonieldasilva** [comment]
@shettyrahul8june did you figure out what is going on? I am getting the same error 🗡

**Comment by shettyrahul8june** [comment]
@jonieldasilva I can still see the error but fortunately, it doesn't mess up with the project. I see only when I start the simulator. After that, I can continue developing without any errors. So for now, I just ignore that error.

**Comment by williamwlchan** [comment]
I have this issue too. Reset content of the ios simulator does work but every time we need to perform this. Any permanent solution?
