### ISSUE TITLE
Background Location in iOS

### ISSUE THREAD

**Issue by bbar** [exponentjs/xde#67]
It looks like `Exponent.Permissions.askAsync(Permissions.LOCATION)` only asks for user location while using the app. To obtain location data while the app is backgrounded we need to set the `NSLocationAlwaysUsageDescription` key in `Info.plist`. I looked in `exp.json` but couldn't find anything. Is this a supported feature?

**Comment by brentvatne** [comment]
Background geolocation is a lot more complex than just enabling this option, unfortunately. We are planning on building it but don't have an ETA.

If you just use React Native (without Exponent), you can use this for iOS: https://github.com/transistorsoft/react-native-background-geolocation -- the Android version of it is costs $300 per app, though (hey if it saves you that much time maybe it's worth it!). We'll be building something similar to this for Exponent.

**Comment by bbar** [comment]
I've only tested this in the simulator, but if I create a new React Native project like so:

    $ react-native init geolocation_test

And then change `index.ios.js` to the following: https://gist.github.com/bbar/f058cfb7d82cd9b465d2c82fac3d9046

The location will be logged in the console while the app is in use. If it's backgrounded, however, then it stops. But if I modify `Info.plist` in the following way, location seems to work fine while the app is backgrounded:

Remove the default `NSLocationWhenInUseUsageDescription` key and add `NSLocationAlwaysUsageDescription` instead. It will work like this, but I've also added the key, `UIBackgroundModes`, which is an array. I've set Item 0 to type `string` and value to `location`.

I haven't messed with this on the Android side at all, and I know your goal with Exponent is to incorporate both platforms, which I think is great, but am I missing something on the iOS side? I assume battery life is a concern, as it is with me.

**Comment by ide** [comment]
The App Store policies are also a concern, each app that uses `NSLocationAlwaysUsageDescription` must explain in the app description how/why the app uses your background location and must include a disclaimer that it hurts battery life. We don't yet have a way for different developers to specify that info when Exponent builds IPAs for them, we support just the common case.

**Comment by bbar** [comment]
Alright, cool -- thanks for the responses, guys. I think we can close this issue. Background location is definitely a fringe case use, but unfortunately I'm writing a fleet management app so without it, I'm dead in the water using Exponent. I'll definitely give it a shot again with my next project. Keep up the great work!

**Comment by haani** [comment]
Hey all, curious if there's any movement on this for android or if there's anything on the roadmap?

**Comment by jesseruder** [comment]
We haven't started working on it yet. For now you can detach and use ExpoKit if you need it.

**Comment by haani** [comment]
Gotcha. Thanks @jesseruder.

**Comment by Palisand** [comment]
Is there still no rough ETA on this? Glad to see its on [canny](https://expo.canny.io/feature-requests/p/background-location-tracking) though.

**Comment by brentvatne** [comment]
this is a big project, we're currently working on building infrastructure into the expo client to support background tasks in general, and then we will build apis like background geolocation on top of that. we don't have an ETA

**Comment by Palisand** [comment]
@brentvatne thanks for the prompt reply
