### ISSUE TITLE
Bundle Exponent app binaries for simulator with xde and then make it so you can launch in the simulator with one click from xde

### ISSUE THREAD

**Issue by ccheever** [exponentjs/xde#7]
We need to do this!

I'm afraid we need a binary for each size of iPhone/iPad (since they use different simulators?) and for each version of Exponent so it could combinatorially explode, but hopefully with fastlane we can manage it reasonably, and the binary won't become too big.

We could also potentially download these on demand instead of downloading all the simulator binaries up front.

**Comment by ide** [comment]
> we need a binary for each size of iPhone/iPad

this still confuses me because when building an IPA with fastlane, the most you can do is select CPU arch but not the acutal device type. I would expect our IPAs to run everywhere as long as we build for x64.

**Comment by ccheever** [comment]
This is just based on the experience I had making a simulator build for exp earlier. If we don't have to, that will be wonderful. Worst case: we have to patch fastlane to get it to build simulator builds.

**Comment by brentvatne** [comment]
:+1: I think this will be an incredibly useful feature

**Comment by ccheever** [comment]
Done as of the latest release!
